// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CampfireController from "./campfire_controller"
application.register("campfire", CampfireController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import RevealController from "./reveal_controller";
application.register("reveal", RevealController);
